version: "3.7"

services:
  jenkins:
    image: "jenkins/jenkins:latest"
    restart: always
    container_name: jenkins
    user: root
    volumes:
    - ~/devops/jenkins_data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops_web_network

networks:
  devops_web_network:
    external: true